#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
# Zpresto is installed as a submodule

cd "$HOME" || exit


system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    read -p "Install homebrew (y/n)? " answer
    case ${answer:0:1} in
      y|Y )
          echo "Installing homebrew"
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew update
          # Check if we brewfile exists then install it
          if [ -f "$HOME/.config/Brewfile" ]; then
            read -p "Install brewfile apps (y/n)?" answer
            case ${answer:0:1} in
                y|Y )
                    echo "Installing homebrew bundle"
                    brew bundle --file="$HOME/.config/Brewfile"
                    brew cleanup
                ;;
                * )
                ;;
            esac
          fi

    ;;
    * )
    ;;
    esac
  fi
fi

echo "Init submodules"
yadm submodule update --recursive --init

# Default shell to zsh
read -p "Change default shell to zsh (y/n)?" answer
case ${answer:0:1} in
  y|Y )
    echo "Setting shell to zsh"
    sudo chsh -s '$(which zsh)' '$USER'
  ;;
  * )
  ;;
esac
